# Spring配置
spring:
  #main:
  #  web-application-type: none # 非web启动
  application:
    name: ahead-soc
  profiles:
    #active: kafka,elastic,redis, dp
    active: logging, ds, kafka, redis,elastic,dp,dw, ia, cep, alarm
  main:
    # allow spring circle ref
    allow-circular-references: true
server:
  port: 8080
  servlet:
    context-path: /soc
logging:
  config: classpath:logback-spring.xml

soc:
  # 收到kafka消息后的处理线程数量。收到kafka消息后,接收线程会启动新线程处理数据，避免接收阻塞.
  handle-threads: 4
  handle-thread-name: soc-handle