soc:
  dp: # 充当dp角色时的配置
    enable: true # 是否充当DP角色
    id: 1
    refill-thread: 4 # 回填线程数量
    topics:
      - topic: ahead-soc-eventbase-collector # 主题名称
        message-type: PROTOBUF # 主题消息类型
        event-type: EVENT # 主题的事件类型
        producer: ahead-soc-eventbase-dp,yangfei-soc-test # 对应的生产主题多个逗号分隔
    modules: # 回填业务处理模块
      csf: # csf回填
        enable: false
        type: redis # 回填类型,目前仅支持redis
        redis-index: soc_csf # redis中的索引
        field-key: raw_id|sensor_model # 查询key,多个以|分隔
        fill-if-not-null: false # 如果不为null时,是否回填
        field-mapping:
          clazz: b
      srcipv4_asset: # 源IP回填
        enable: true # 是否回填org
        type: redis # 回填类型,目前仅支持redis
        redis-index: soc_assets # redis中的索引
        redis-key: int_srcipv4 # 查询key,多个以|分隔
        fill-if-not-null: true # 如果不为null时,是否回填
        fields: # 回填字段
          srcAssetId: id # key为eventbase中的字段名,value为redis中JSON格式的key
          srcAssetLevel: assetsLevel
          srcOrgId: deptId
        exclude-topics:
          - ahead-soc-eventbase-collector
      srcipv4_business: # 源业务系统回填
        enable: false # 是否回填org
        type: redis # 回填类型,目前仅支持redis
        redis-index: soc_business # redis中的索引
        redis-key: int_srcipv4|srcport # 查询key,多个以|分隔
        field-key-join: ":" # redisKey值的拼接方式,默认为"_"
        fill-if-not-null: true # 如果不为null时,是否回填
        fields: # 回填字段
          srcBusiName: systemName # key为eventbase中的字段名,value为redis中JSON格式的key
          srcBusiId: id
      dstipv4_asset: # 目的业务系统回填
        enable: false # 是否回填org
        type: redis # 回填类型,目前仅支持redis
        redis-index: soc_assets # redis中的索引
        redis-key: int_dstipv4 # 查询key,多个以|分隔
        fill-if-not-null: true # 如果不为null时,是否回填
        fields: # 回填字段
          dstAssetId: id # key为eventbase中的字段名,value为redis中JSON格式的key
          dstAssetLevel: assetsLevel
          dstOrgId: deptId
      dstipv4_business: # 目的业务系统回填
        enable: false # 是否回填org
        type: redis # 回填类型,目前仅支持redis
        redis-index: soc_business # redis中的索引
        redis-key: int_dstipv4|dstport # 查询key,多个以|分隔
        redis-key-join: ":" # redisKey值的拼接方式,默认为"_"
        fill-if-not-null: true # 如果不为null时,是否回填
        fields: # 回填字段
          srcBusiName: systemName # key为eventbase中的字段名,value为redis中JSON格式的key
          srcBusiId: id
      GEO: # GEO 回填配置
         enable: true # 是否回填org
         ipFields: # ip字段
           src: srcipv4
           dst: dstipv4
    monitor: # 状态监控,暂未实现
      enable: false